### PR TITLE
pt-locale

### PR DESCRIPTION
**Pull request by ocefpaf**
Far from ready!  Just testing...

### CODE REVIEW

**Comment by rgaiacs** [comment]
@ocefpaf Thanks. Can I merge it?

**Comment by ocefpaf** [comment]
I am not done.  And I also need to solve the merge conflicts.  It should be ready after 13:00 today.  (I am stuck with some emergencies at the day job.)

**Comment by ocefpaf** [comment]
@rgaiacs and @xmnlab after a (painful) rebase against master I belive this is ready for a review.  Hopefully I did not screw things up!

(If that happens we can close this PR and I can start over from master.)

**Comment by rgaiacs** [comment]
> after a (painful) rebase against master

Sorry for the painful rebase. If there is something that we can do for avoid it in the future let us know.

**Comment by ocefpaf** [comment]
> Sorry for the painful rebase. If there is something that we can do for
> avoid it in the future let us know.

It is in part my fault for taking longer than I expected to translate. But
we can coordinate the PRs and avoid committing directly to master.

**Comment by rgaiacs** [comment]
@ocefpaf THANKS for the translation. :sparkles: :sparkling_heart: :sparkles: 

You can check it at http://test.scipyla.org/scipyla2016/. We will deploy it for production soon.

**Comment by ocefpaf** [comment]
> You can check it at http://test.scipyla.org/scipyla2016/.

Will do.

> We will deploy it for production soon.

Oh... Oh...  I need to re-review that before.  I believe there are a few rough edges in need of repair.

**Comment by rgaiacs** [comment]
Maybe @melissawm could do the re-review. Just go to http://test.scipyla.org/scipyla2016/ and check. The machine/web browser that you use need to be configure to use Portuguese as the language.

**Comment by melissawm** [comment]
I'm a little lost on the actual code and I'm not sure where to fix this, but the sponsorship text to the left of the main page is in english to me, even when the rest of the page is in pt_br. It should read something like

SciPyLA 2016 precisa de patrocinadores. Para apoiar este evento, por favor entre em contato: scipy-organizers@scipy.org

Veja o Prospecto de Patrocínio da SciPyLA 2016 para informações mais detalhadas.

**Comment by xmnlab** [comment]
maybe this text is inserted into database ... maybe something related to sitetree ...

**Pull request merged**
