### PR TITLE
Add Friends

### PR DESCRIPTION
**Pull request by rgaiacs**
# TODO
- [X] Query database
- [x] Improve CSS
- [ ] Translate

### CODE REVIEW

**Comment by rgaiacs** [comment]
@xmnlab I want to improve the CSS (add columns) and manage the friends as partners (not embed).

**Comment by rgaiacs** [comment]
@xmnlab Could you review this?

@leportella Comments?

screen shot 2016-02-10 at 11 21 45

**Comment by leportella** [comment]
Curti

**Comment by xmnlab** [comment]
muito bom! :)

**Pull request merged**
